import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

import { handleDirectToHome } from '../utils/redirect';

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    handleDirectToHome(router);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/hotel.ico" />
      </Head>
      <div></div>
    </>
  );
}
